export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "secondary-fixed": "#d1e4ff",
        "on-tertiary-container": "#008eab",
        "background": "#121317",
        "surface": "#121317",
        "outline": "#8e9196",
        "on-primary": "#263046",
        "secondary": "#afc9ea",
        "on-secondary-fixed": "#001d36",
        "on-primary-fixed": "#101b30",
        "primary-fixed": "#d7e2ff",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#b3ebff",
        "surface-dim": "#121317",
        "secondary-container": "#2f4865",
        "surface-container-low": "#1a1b20",
        "surface-variant": "#343439",
        "on-tertiary-fixed-variant": "#004e5f",
        "surface-container-lowest": "#0d0e12",
        "on-primary-fixed-variant": "#3c475d",
        "outline-variant": "#44474c",
        "surface-tint": "#bbc6e2",
        "secondary-fixed-dim": "#afc9ea",
        "primary-fixed-dim": "#bbc6e2",
        "surface-container-high": "#292a2e",
        "on-secondary": "#17324d",
        "error": "#ffb4ab",
        "surface-bright": "#38393e",
        "primary": "#bbc6e2",
        "on-surface": "#e3e2e8",
        "error-container": "#93000a",
        "surface-container-highest": "#343439",
        "on-error": "#690005",
        "surface-container": "#1f1f24",
        "inverse-surface": "#e3e2e8",
        "inverse-on-surface": "#2f3035",
        "on-secondary-fixed-variant": "#2f4865",
        "on-secondary-container": "#9eb7d8",
        "on-background": "#e3e2e8",
        "on-primary-container": "#78839c",
        "inverse-primary": "#545e76",
        "tertiary-fixed-dim": "#4cd6fb",
        "primary-container": "#0f1a2e",
        "on-tertiary": "#003642",
        "on-tertiary-fixed": "#001f27",
        "on-surface-variant": "#c4c6cc",
        "tertiary": "#4cd6fb",
        "tertiary-container": "#001d25"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
